### ISSUE TITLE
Reading hdf5 HELP

### ISSUE THREAD

**Issue by Marco-Pellegrino** [Apollo3zehn/PureHDF#36]
Hi @Apollo3zehn 

I would like to use your library to read my .hdf5 file but I am having issue in understanding the "group" or "dataset" or "attribute".

Can you provide a quick example that reference my file?

Thanks,
Marco

![image](https://github.com/Apollo3zehn/PureHDF/assets/53620289/779b865c-ffd2-489c-80cb-d3cad8eeed3d)
[recorder.zip](https://github.com/Apollo3zehn/PureHDF/files/12095206/recorder.zip)

**Comment by Apollo3zehn** [comment]
For example to read the dataset `COORDINATES` (which is of type `double`) located in group `/MODEL_STAGE[1]/MODEL/NODES/` (the folder symbols are groups), you would to the following:

```cs
using var root = NativeFile.OpenRead("<your file>.h5");

var dataset = root.Group("/MODEL_STAGE[1]/MODEL/NODES").Dataset("COORDINATES");

var data = dataset
    .Read<double>()
    .ToArray2D(dim0: 264, dim1: -1 /* auto-calculated */);
```
Here is an overview over HDF View:

![grafik](https://github.com/Apollo3zehn/PureHDF/assets/20972129/a2e6f793-2169-4754-8f85-ae753af24c64)

And here is the result of the sample code above. It shows that PureHDF could read the data of the "COORDINATES" dataset:

![grafik](https://github.com/Apollo3zehn/PureHDF/assets/20972129/d4b3f0f5-b35f-428f-80ee-95b028997cc2)

Attributes work similar in that instead of calling `.Dataset(<dataset name>) you would call `.Attribute(<attribute name>)`. Attributes are very small datasets that often consists of single values. Conceptually attributes are some kind of metadata. You can also view them with HDFView.

![grafik](https://github.com/Apollo3zehn/PureHDF/assets/20972129/bfd72fde-e178-49e3-8724-cae93c460b20)

I hope this helps you to get started.

**Comment by Marco-Pellegrino** [comment]
thanks a lot @Apollo3zehn !

It is definitely way easier to understand the structure now!

I also found the following way to get access to the dataset.

```csharp
using var h5File = PureHDF.H5File.OpenRead(@"HDF5\recorder.hdf5");

var dataset = h5File.Dataset("/MODEL_STAGE[1]/RESULTS/ON_NODES/DISPLACEMENT/DATA/STEP_0");
var dimX = (long)dataset.Space.Dimensions[0];
var dimY = (long)dataset.Space.Dimensions[1];

var values = dataset.Read<double>().ToArray2D(dimX, dimY);
```


Your tool is super apreciated as I can finally read hdf5 file from my M2 mac

**Comment by Apollo3zehn** [comment]
Glad it helped you! You are right, your way is simpler :D 

I am working on a simple writing implementation, too, and then I hopefully can finally release v1.
